sonar.projectKey=higress-group_higress-console
sonar.organization=higress-group
sonar.host.url=https://sonarcloud.io
sonar.sources=backend/src/main/java,frontend/src
sonar.tests=backend/src/test/java,frontend/src
sonar.java.binaries=backend/target/classes
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
